#!/bin/bash

cd /srv/enigmatick

if [[ -z ${ENIGMATICK_ROLE} ]]; then
    echo "Assuming server role..."
    ./enigmatick server
else
    if [ "$ENIGMATICK_ROLE" == "runner" ]; then
	      ./enigmatick runner
    else
	      ./enigmatick server
    fi
fi

