ALTER TABLE activities_cc ALTER COLUMN ap_id SET DATA TYPE VARCHAR;
ALTER TABLE activities_to ALTER COLUMN ap_id SET DATA TYPE VARCHAR;
ALTER TABLE timeline_to ALTER COLUMN ap_id SET DATA TYPE VARCHAR;
ALTER TABLE timeline_cc ALTER COLUMN ap_id SET DATA TYPE VARCHAR;
ALTER TABLE remote_actors ALTER COLUMN inbox SET DATA TYPE VARCHAR;
ALTER TABLE remote_actors ALTER COLUMN outbox SET DATA TYPE VARCHAR;
ALTER TABLE remote_actors ALTER COLUMN followers SET DATA TYPE VARCHAR;
ALTER TABLE remote_actors ALTER COLUMN following SET DATA TYPE VARCHAR;
ALTER TABLE remote_actors ALTER COLUMN liked SET DATA TYPE VARCHAR;
ALTER TABLE remote_actors ALTER COLUMN featured SET DATA TYPE VARCHAR;
ALTER TABLE remote_actors ALTER COLUMN url SET DATA TYPE VARCHAR;
ALTER TABLE activities ALTER COLUMN actor SET DATA TYPE VARCHAR;
ALTER TABLE activities ALTER COLUMN target_ap_id SET DATA TYPE VARCHAR;
ALTER TABLE activities ALTER COLUMN ap_id SET DATA TYPE VARCHAR;

