DROP INDEX idx_remote_note_hashtags_hashtag;
DROP INDEX idx_note_hashtags_hashtag;
DROP INDEX idx_remote_actor_hashtags_hashtag;
DROP INDEX idx_profile_hashtags_hashtag;
DROP INDEX idx_timeline_hashtags_hashtag;
